INSERT INTO hsg.tb_especialidade (nm_especialidade, ds_especialidade, area_especialidade, st_especialidade, dt_cad_especialidade)
VALUES
    ('Acupuntura',                          'Prática integrativa de estimulação de pontos corporais.',         'CLINICA',    'A', NOW()),
    ('Alergia e Imunologia',                'Diagnóstico e tratamento de doenças alérgicas e imunológicas.',   'CLINICA',    'A', NOW()),
    ('Anestesiologia',                      'Anestesia e controle da dor perioperatória.',                     'CIRURGIA',   'A', NOW()),
    ('Angiologia',                          'Doenças dos vasos sanguíneos e linfáticos.',                      'CLINICA',    'A', NOW()),
    ('Cancerologia / Oncologia',            'Diagnóstico e tratamento do câncer.',                             'CLINICA',    'A', NOW()),
    ('Cirurgia Cardiovascular',             'Cirurgia do coração e grandes vasos.',                            'CIRURGIA',   'A', NOW()),
    ('Cirurgia de Cabeça e Pescoço',        'Cirurgia das estruturas da cabeça e pescoço.',                    'CIRURGIA',   'A', NOW()),
    ('Cirurgia do Aparelho Digestivo',      'Cirurgia do trato gastrointestinal.',                             'CIRURGIA',   'A', NOW()),
    ('Cirurgia Geral',                      'Procedimentos cirúrgicos gerais.',                                'CIRURGIA',   'A', NOW()),
    ('Cirurgia da Mão',                     'Cirurgia reconstrutiva e reparadora da mão.',                     'CIRURGIA',   'A', NOW()),
    ('Cirurgia Plástica',                   'Cirurgia estética e reconstrutiva.',                              'CIRURGIA',   'A', NOW()),
    ('Cirurgia Torácica',                   'Cirurgia dos órgãos do tórax.',                                   'CIRURGIA',   'A', NOW()),
    ('Cirurgia Vascular',                   'Cirurgia dos vasos sanguíneos periféricos.',                      'CIRURGIA',   'A', NOW()),
    ('Coloproctologia',                     'Doenças do cólon, reto e ânus.',                                  'CLINICA',    'A', NOW()),
    ('Dermatologia',                        'Doenças da pele, cabelo e unhas.',                                'CLINICA',    'A', NOW()),
    ('Endocrinologia e Metabologia',        'Distúrbios hormonais e metabólicos.',                             'CLINICA',    'A', NOW()),
    ('Endoscopia',                          'Diagnóstico e terapêutica endoscópica.',                          'DIAGNOSTICO','A', NOW()),
    ('Gastroenterologia',                   'Doenças do aparelho digestivo.',                                  'CLINICA',    'A', NOW()),
    ('Genética Médica',                     'Diagnóstico e tratamento de doenças genéticas.',                  'CLINICA',    'A', NOW()),
    ('Geriatria',                           'Atenção à saúde do idoso.',                                       'CLINICA',    'A', NOW()),
    ('Ginecologia e Obstetrícia',           'Saúde da mulher e gestação.',                                     'CLINICA',    'A', NOW()),
    ('Hematologia e Hemoterapia',           'Doenças do sangue e transfusão.',                                 'CLINICA',    'A', NOW()),
    ('Hepatologia',                         'Doenças do fígado e vias biliares.',                              'CLINICA',    'A', NOW()),
    ('Infectologia',                        'Doenças infecciosas e parasitárias.',                             'CLINICA',    'A', NOW()),
    ('Mastologia',                          'Doenças da mama.',                                                'CLINICA',    'A', NOW()),
    ('Medicina de Emergência',              'Atendimento de urgências e emergências.',                         'CLINICA',    'A', NOW()),
    ('Medicina de Família e Comunidade',    'Atenção primária à saúde.',                                       'CLINICA',    'A', NOW()),
    ('Medicina Intensiva',                  'Cuidados intensivos ao paciente crítico.',                        'CLINICA',    'A', NOW()),
    ('Medicina Legal e Perícia Médica',     'Aplicação da medicina ao direito.',                               'CLINICA',    'A', NOW()),
    ('Medicina Nuclear',                    'Diagnóstico e terapia com radioisótopos.',                        'DIAGNOSTICO','A', NOW()),
    ('Medicina Preventiva e Social',        'Promoção da saúde e prevenção de doenças.',                       'CLINICA',    'A', NOW()),
    ('Medicina do Trabalho',               'Saúde do trabalhador e medicina ocupacional.',                    'CLINICA',    'A', NOW()),
    ('Medicina do Esporte',                'Saúde, desempenho e lesões no esporte.',                          'CLINICA',    'A', NOW()),
    ('Nefrologia',                          'Doenças dos rins.',                                               'CLINICA',    'A', NOW()),
    ('Neurocirurgia',                       'Cirurgia do sistema nervoso.',                                    'CIRURGIA',   'A', NOW()),
    ('Nutrologia',                          'Distúrbios nutricionais e alimentares.',                          'CLINICA',    'A', NOW()),
    ('Oftalmologia',                        'Doenças dos olhos.',                                              'CLINICA',    'A', NOW()),
    ('Ortopedia e Traumatologia',           'Aparelho locomotor e trauma.',                                    'CIRURGIA',   'A', NOW()),
    ('Otorrinolaringologia',                'Doenças do ouvido, nariz e garganta.',                            'CLINICA',    'A', NOW()),
    ('Patologia',                           'Diagnóstico morfológico de doenças.',                             'DIAGNOSTICO','A', NOW()),
    ('Pneumologia',                         'Doenças do aparelho respiratório.',                               'CLINICA',    'A', NOW()),
    ('Psiquiatria',                         'Transtornos mentais e comportamentais.',                          'CLINICA',    'A', NOW()),
    ('Radiologia e Diagnóstico por Imagem', 'Diagnóstico por métodos de imagem.',                             'DIAGNOSTICO','A', NOW()),
    ('Radioterapia',                        'Tratamento do câncer com radiação.',                              'CLINICA',    'A', NOW()),
    ('Reumatologia',                        'Doenças do sistema musculoesquelético e autoimunes.',             'CLINICA',    'A', NOW()),
    ('Urologia',                            'Doenças do trato urinário e sistema reprodutor masculino.',       'CLINICA',    'A', NOW())
ON CONFLICT (nm_especialidade) DO NOTHING;
